"""initial schema — the full current model set.

Generated from `backend.database.models` metadata, so it matches what the
app's own `init_db()` creates: 12 tables including `system_settings` and the
`predictions.pick_score` / `predictions.score_label` columns.

A fresh deploy does not need this file — `init_db()` runs at startup. It
exists so later schema changes are ordered and reviewable:

    alembic revision --autogenerate -m "add X"
    alembic upgrade head

Revision ID: 20906bce9629
Revises: 
Create Date: 2026-08-20 21:50:43.400348

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20906bce9629'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankroll',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('total_staked', sa.Float(), nullable=False),
    sa.Column('total_won', sa.Float(), nullable=False),
    sa.Column('total_profit', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmakers',
    sa.Column('bookmaker_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('bookmaker_id')
    )
    op.create_table('markets',
    sa.Column('market_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('market_id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('league', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('system_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=True),
    sa.Column('match_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency', sa.Float(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('agent_analyses',
    sa.Column('analysis_id', sa.String(length=50), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('bets',
    sa.Column('bet_id', sa.String(length=50), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('selection', sa.String(length=100), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('bookmaker', sa.String(length=50), nullable=True),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('potential_profit', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('bet_id')
    )
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('bookmaker', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('selection', sa.String(length=100), nullable=False),
    sa.Column('line', sa.String(length=20), nullable=True),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(length=50), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('selection', sa.String(length=100), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('bookmaker', sa.String(length=50), nullable=True),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('implied_probability', sa.Float(), nullable=False),
    sa.Column('edge', sa.Float(), nullable=False),
    sa.Column('ev', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('pick_score', sa.Float(), nullable=True),
    sa.Column('score_label', sa.String(length=30), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('risk_assessments',
    sa.Column('assessment_id', sa.String(length=50), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=True),
    sa.Column('bankroll_risk_percent', sa.Float(), nullable=False),
    sa.Column('exposure', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('correlation_risk', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('veto_decision', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('simulations',
    sa.Column('simulation_id', sa.String(length=50), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('home_win_probability', sa.Float(), nullable=False),
    sa.Column('draw_probability', sa.Float(), nullable=False),
    sa.Column('away_win_probability', sa.Float(), nullable=False),
    sa.Column('handicap_probability', sa.Float(), nullable=True),
    sa.Column('over_probability', sa.Float(), nullable=True),
    sa.Column('under_probability', sa.Float(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('simulation_count', sa.Integer(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulations')
    op.drop_table('risk_assessments')
    op.drop_table('predictions')
    op.drop_table('odds_snapshots')
    op.drop_table('bets')
    op.drop_table('agent_analyses')
    op.drop_table('system_settings')
    op.drop_table('system_logs')
    op.drop_table('matches')
    op.drop_table('markets')
    op.drop_table('bookmakers')
    op.drop_table('bankroll')
    # ### end Alembic commands ###
